// Imports
const AWS = require('aws-sdk');
const express = require('express');
const { v4: uuidv4 } = require('uuid');

// Express
const router = express.Router();

// AWS
const AWS_REGION_NAME = 'ap-southeast-1';
AWS.config.update({ region: AWS_REGION_NAME });
const S3 = new AWS.S3();

// Constants
const { PHOTO_BUCKET_NAME } = process.env;
const LINK_EXPIRY = 300; // in seconds

/**
 * @api {get} /photos/presigned-url
 * @apiVersion 0.1.0
 * @apiName obtainS3UploadLink
 * @apiGroup Photos
 * @apiDescription This endpoint calls the S3 API to get a presigned URL for the frontend to
 * upload a photo to.
 *
 * This method currently resides in the Photos group, but it might be merged into HealthReport.
 * @apiPermission To be decided
 *
 * @apiError To be decided
 *
 * @apiHeader To be decided
 *
 * @apiParam To be decided
 *
 * @apiSuccess {String} path S3 path of that the photo is stored in
 * @apiSuccess {String} preSignedUrl PreSigned URL generated by AWS SDK that the client puts to
 * @apiSuccessExample {json} Success-Response:
 *     HTTP/1.1 200 OK
 *     {
 *       "path": "test",
 *       "preSignedUrl": "https://test.s3.ap-southeast-1.amazonaws.com/testAWSAccessKeyId=testExpires=test&Signature=test"
 *     }
 */
async function obtainS3UploadLink(req, res) {
  // We might need an agency identifier to separate photos from different groups of users
  const path = uuidv4();

  try {
    // Construct a request
    const request = {
      Bucket: PHOTO_BUCKET_NAME,
      Key: path,
      Expires: LINK_EXPIRY,
    };

    S3.getSignedUrl('putObject', request, (err, preSignedUrl) => {
      res.status(200).send({
        path,
        preSignedUrl,
      });
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
}

router.get('/presigned-url', obtainS3UploadLink); // This needs to include auth middleware later

module.exports = router;
